repos:
  -   repo: local
      hooks:
        -   id: black
            name: black
            entry: black
            language: system
            types: [python]
        -   id: pycodestyle
            name: pycodestyle
            entry: pycodestyle --ignore=E501,W605,W504 --max-doc-length=160
            language: system
            types: [python]
