name: Publish to PyPI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main, refactoring]

jobs:
  build_production:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install full package
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip wheel poetry==1.5.1 poetry-dynamic-versioning
          ./poetry_wrapper.sh cache clear pypi --all
          ./poetry_wrapper.sh install --all-extras

      - name: Build
        run: |
          . ./venv/bin/activate
          export PACKAGE_SUFFIX=.dev
          ./poetry_wrapper.sh --generate
          ./poetry_wrapper.sh build

  build_experimental:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install full package
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip wheel poetry==1.5.1 poetry-dynamic-versioning lightfm==1.17
          ./poetry_wrapper.sh cache clear pypi --all
          ./poetry_wrapper.sh --experimental install --all-extras

      - name: Build
        run: |
          . ./venv/bin/activate
          export PACKAGE_SUFFIX=.preview
          ./poetry_wrapper.sh --experimental --generate
          ./poetry_wrapper.sh build
