name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main, refactoring]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install --upgrade pip wheel poetry==1.5.1 lightfm

          poetry cache clear pypi --all
          poetry install
      - name: Build docs
        run: |
          . ./venv/bin/activate
          make -C docs clean html
      - name: pycodestyle
        run: |
          . ./venv/bin/activate
          pycodestyle replay tests
      - name: pylint
        run: |
          . ./venv/bin/activate
          pylint replay
      - name: pytest
        run: |
          . ./venv/bin/activate
          pytest
