name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main, refactoring]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install full package
        run: |
          pip install --upgrade pip wheel poetry==1.5.1 lightfm

          poetry cache clear pypi --all
          ./poetry_wrapper.sh --experimental install --all-extras
      - name: Build docs
        run: make -C docs clean html
      - name: pycodestyle
        run: pycodestyle replay tests
      - name: pylint
        run: pylint replay
      - name: pytest
        run: pytest
